# Generated by Django 5.0.6 on 2024-06-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[("RU", "Russian"), ("KZ", "Kazakh")], max_length=2
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "parent_first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "parent_last_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "parent_phone_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Almaty", "Алматы"),
                            ("Astana", "Астана"),
                            ("Shymkent", "Шымкент"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные клиента",
                "verbose_name_plural": "Данные клиентов",
            },
        ),
    ]
